### ISSUE TITLE
headers["Authorization"] = auth_template % {"value": self.auth["accessToken"]}

### ISSUE THREAD

**Issue by MominIqbal-1234** [Simatwa/WebChatGPT#14]
i  get the cookies this extension
https://chromewebstore.google.com/detail/export-cookie-json-file-f/nmckokihipjgplolmcmjakknndddifde

### Error
end_auth
    headers["Authorization"] = auth_template % {"value": self.auth["accessToken"]}
KeyError: 'accessToken'

**Comment by Simatwa** [comment]
Same issue over here. I will try to fix it asap.
