### ISSUE TITLE
Failed to fetch conversation history

### ISSUE THREAD

**Issue by elcoan** [Simatwa/WebChatGPT#16]
Hello, today i got an error:

```
  File "C:\Python\Lib\site-packages\WebChatGPT\main.py", line 102, in current_conversation_id
    self.previous_conversations(
  File "C:\Python\Lib\site-packages\WebChatGPT\main.py", line 514, in previous_conversations
    resp = utils.is_json(resp, "conversation history")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\WebChatGPT\utils.py", line 153, in is_json
    raise Exception(
Exception: Failed to fetch conversation history - `text/html; charset=UTF-8` :
```

Could you please help me?

**Comment by 11100010** [comment]
I'm not sure if we have the same error:

> [1] % wbc interactive hola                                                           351ms
╭─────────────────────────────────── WebChatGPT v0.3.0 ────────────────────────────────────╮
│                                                                                          │
│             Repo : https://github.com/Simatwa/WebChatGPT                                 │
│             By : Smartwa                                                                 │
│                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
18:01:05 - ERROR : Failed to fetch Auth value (403, Forbidden), supply path to correct cookies.  Incase you have no idea on how to get the cookies check the documentation at -     https://github.com/Simatwa/WebChatGPT - None

pretty sure that the cookies setup is right.

**Comment by Simatwa** [comment]
The ChatGPT's web backend is constantly maintained and some changes tend to render this script unused. Currently fixed. Otherwise thanks for raising this.

**Comment by Simatwa** [comment]
The ChatGPT's web backend is constantly maintained and some changes tend to render this script unused. Currently fixed. Otherwise thanks for raising this.
