### ISSUE TITLE
RequestsJSONDecodeError on ChatGPT(...)

### ISSUE THREAD

**Issue by Almas-Ali** [Simatwa/WebChatGPT#2]
```python
from WebChatGPT import ChatGPT


bot = ChatGPT(
    "chat.openai.com.cookies.json",
)

response = bot.ask('Hello, how are you?')
print(response)
```

```
Traceback (most recent call last):
  File "**/.venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**/main.py", line 4, in <module>
    bot = ChatGPT(
          ^^^^^^^^
  File "**/.venv/lib/python3.11/site-packages/WebChatGPT/main.py", line 35, in __init__
    self.session.headers.update(utils.get_request_headers_and_append_auth(self))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "**/.venv/lib/python3.11/site-packages/WebChatGPT/utils.py", line 64, in get_request_headers_and_append_auth
    self.auth = resp.json()
                ^^^^^^^^^^^
  File "**/.venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
```

I think you need to use `pydantic` to easily handle those JSON responses as a Python model. I am highly interested in this project and would like to test it out. I did think about this month but didn't get much time to do so.

**Comment by Simatwa** [comment]
Thanks for that. Could you possibly give it a PR?

**Comment by Almas-Ali** [comment]
Will try.

**Comment by Almas-Ali** [comment]
@Simatwa do you use discord or telegram? We may talk there. Drop your account handle here for sometime then delete it.

**Comment by Simatwa** [comment]
I prefer not to share bruh.

**Comment by tobwen** [comment]
That's easy to fix:
https://github.com/Simatwa/WebChatGPT/blob/d6a124a957fe70bee50e74635cdf0d889c4a1cd7/WebChatGPT/utils.py#L15

You're requesting a compressed response, but you're not uncompressing it. Either comment this out (which might be detected by OpenAI) or uncompress the response.

**Comment by Simatwa** [comment]
B

> That's easy to fix:
> 
> https://github.com/Simatwa/WebChatGPT/blob/d6a124a957fe70bee50e74635cdf0d889c4a1cd7/WebChatGPT/utils.py#L15
> 
> You're requesting a compressed response, but you're not decompressing it. Either comment this out (which might be detected by OpenAI) or decompress the response.

Commenting it out might cause detection especially through user-agent leaks. [Brotli](https://github.com/google/brotli) auto-handles that if it's installed. I'll add it as one of the dependencies asap.

**Comment by Almas-Ali** [comment]
I tried `brotli` last night but couldn’t make it work. Is it working now?

**Comment by Simatwa** [comment]
On this side. It's a yes.
