### ISSUE TITLE
Firefox vs. Chrome

### ISSUE THREAD

**Issue by tobwen** [Simatwa/WebChatGPT#3]
## recommendation
I'd highly recommend to use a Chrome-based user-agent instead of a Mozilla one.

## explaination
The market-share of Firefox is incredible low, so it might be easy to detect WebChatGPT.
https://gs.statcounter.com/browser-market-share

**Comment by Simatwa** [comment]
That's true Chrome is dominating. But now using Chrome user-agents to make requests using cookies assigned to Firefox user-gents will trigger Cloudflare captcha challenge.
