### ISSUE TITLE
Cookie Auth Fetching Issue

### ISSUE THREAD

**Issue by 5l1v3r1** [Simatwa/WebChatGPT#6]
I am on python 3.9 windows and the exported json file export-cookie-for-puppeteer extension is not accepted by webchatgpt 

"Enter path to .json file containing cookies for `chat.openai.com`: chat.openai.com.cookies.json
11:24:24 - ERROR : Failed to fetch Auth value, supply path to correct cookies.  Incase you have no idea on how to get the cookies check the documentation at -     https://github.com/Simatwa/WebChatGPT - None"

why cannot it fetch the values?

**Comment by Simatwa** [comment]
I've tried fixing it but unfortunately I can't even figure out the cause of the bug. Hope folks gonna try out. At the moment let's settle for other later versions.

**Comment by Simatwa** [comment]
https://github.com/Simatwa/WebChatGPT/blob/7641f3328699fef4c87a6593688f01848c28cf30/docs/README.md?plain=1#L42
