### ISSUE TITLE
What is the name of the model?

### ISSUE THREAD

**Issue by jxyk2007** [Simatwa/WebChatGPT#7]
gpt3.5
gpt4.0 ?

**Comment by Simatwa** [comment]
gpt3.5

**Comment by jxyk2007** [comment]
> gpt3.5


Not supported for gpt4.0

**Comment by Simatwa** [comment]
I'm not sure about that because I haven't tested yet.

**Comment by jxyk2007** [comment]
> I'm not sure about that because I haven't tested yet.

I have a plus account,

I can give you a test

**Comment by Simatwa** [comment]
It will be much better.

**Comment by jxyk2007** [comment]
> It will be much better.
https://t.me/MI_Su7
